/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bus.SanPhamsChecker;
import dao.SanPhamsDao;
import dto.SanPhams;
import java.sql.SQLException;
import java.util.Stack;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static jdk.nashorn.internal.objects.NativeError.printStackTrace;

/**
 *
 * @author nguyentrinhan2000
 */
public class SanPhamsGUI extends javax.swing.JFrame {

    /**
     * Creates new form SanPhamsGUI
     */
    private SanPhamsDao spDao = new SanPhamsDao();
    SanPhamsTableModel<SanPhams> model;

//    private void loadDataToTable() {
//        try {
//            Vector<SanPhams> listSp = new Vector<SanPhams>();
//            // lay ds
//            listSp = spDao.readAll();
//
//            //load dl
//            model.getData().addAll(listSp);
//        } catch (Exception e) {
//            printStackTrace(e);
//            JOptionPane.showMessageDialog(this, e);
//        }
//
//    }
    public SanPhamsGUI() {
        initComponents();
        this.setSize(750, 450);
        int[] indexes = {0, 1, 2, 3, 4};
        String[] headers = {"Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Số lượng", "Trạng thái"};
        model = new SanPhamsTableModel<SanPhams>(headers, indexes);
        this.tblList.setModel(model);

        loadDataToTable();

    }

    private void loadDataToTable() {
        try {
            Vector<SanPhams> listSanPhams = new Vector<SanPhams>();
            listSanPhams = spDao.readAll();
            model.getData().addAll(listSanPhams);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCode = new javax.swing.JTextField();
        jName = new javax.swing.JTextField();
        jQuantity = new javax.swing.JTextField();
        jPrice = new javax.swing.JTextField();
        jCheckBox = new javax.swing.JCheckBox();
        jAdd = new javax.swing.JButton();
        jSave = new javax.swing.JButton();
        jDel = new javax.swing.JButton();
        jNew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblList);

        jLabel1.setText("Mã sản phẩm:");

        jLabel2.setText("Tên sản phẩm:");

        jLabel3.setText("Đơn giá:");

        jLabel4.setText("Số lượng:");

        jPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPriceActionPerformed(evt);
            }
        });

        jCheckBox.setText("Trạng thái");
        jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActionPerformed(evt);
            }
        });

        jAdd.setText("Thêm");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        jSave.setText("Lưu");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        jDel.setText("Xóa");
        jDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDelActionPerformed(evt);
            }
        });

        jNew.setText("Mới");
        jNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jName)
                            .addComponent(jCode)
                            .addComponent(jPrice)
                            .addComponent(jQuantity)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addComponent(jNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jCode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addComponent(jCheckBox)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAdd)
                            .addComponent(jSave)
                            .addComponent(jDel)
                            .addComponent(jNew)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxActionPerformed

    private void jPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPriceActionPerformed

    private void tblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListMouseClicked
        // TODO add your handling code here:
        int pos = tblList.getSelectedRow();
        SanPhams sp = model.getData().get(pos);
        this.jCode.setText(sp.getId());
        this.jName.setText(sp.getName());
        this.jPrice.setText(String.valueOf(sp.getPrice()));
        this.jQuantity.setText(String.valueOf(sp.getQuantity()));
        this.jCheckBox.setSelected(sp.isAvailable());
    }//GEN-LAST:event_tblListMouseClicked

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        String Code = jCode.getText();
        String Name = jName.getText();
        int Price = 0;
        int Quantity = 0;
        if (!jPrice.getText().equals("") && !jQuantity.getText().equals("")) {
            Price = Integer.parseInt(jPrice.getText());
            Quantity = Integer.parseInt(jQuantity.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu");
        }
        boolean Available = jCheckBox.isSelected();
        SanPhams sp = new SanPhams(Code, Name, Price, Quantity, Available);
        //SanPhams sp = new SanPhams(this.jCode.getText(), this.jName.getText(), Integer.getInteger(this.jPrice.getText()), Integer.getInteger(this.jQuantity.getText()), this.jCheckBox.isSelected());
        if (SanPhamsChecker.checkData(sp)) {
            try {
                // create new
                spDao.create(sp);
                //update table
                model.getData().add(sp);
                tblList.updateUI();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "lỗi nhập liệu");
        }
    }//GEN-LAST:event_jAddActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
        // TODO add your handling code here:
        String Code = jCode.getText();
        String Name = jName.getText();
        int Price = 0;
        int Quantity = 0;
        if (!jPrice.getText().equals("") && !jQuantity.getText().equals("")) {
            Price = Integer.parseInt(jPrice.getText());
            Quantity = Integer.parseInt(jQuantity.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu");
        }
        boolean Available = jCheckBox.isSelected();
        SanPhams sp = new SanPhams(Code, Name, Price, Quantity, Available);
        //SanPhams sp = new SanPhams(this.jCode.getText(), this.jName.getText(), Integer.getInteger(this.jPrice.getText()), Integer.getInteger(this.jQuantity.getText()), this.jCheckBox.isSelected());
        if (SanPhamsChecker.checkData(sp) && !jPrice.getText().equals("") && !jQuantity.getText().equals("")) {
            try {
                spDao.update(sp);
                int pos = tblList.getSelectedRow();
                model.getData().set(pos, sp);
                tblList.updateUI();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu");
        }
    }//GEN-LAST:event_jSaveActionPerformed

    private void jDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDelActionPerformed
        // TODO add your handling code here:
        try {
            spDao.delete(jCode.getText());
            int pos = tblList.getSelectedRow();
            model.getData().remove(pos);
            tblList.updateUI();
            // update fields
            jCode.setText("");
            jName.setText("");
            jPrice.setText("");
            jQuantity.setText("");
            jCheckBox.setSelected(false);
            jCode.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jDelActionPerformed

    private void jNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewActionPerformed
        // TODO add your handling code here:
        jCode.setText("");
        jName.setText("");
        jPrice.setText("");
        jQuantity.setText("");
        jCheckBox.setSelected(false);
        jCode.requestFocus();
    }//GEN-LAST:event_jNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPhamsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdd;
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JTextField jCode;
    private javax.swing.JButton jDel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jName;
    private javax.swing.JButton jNew;
    private javax.swing.JTextField jPrice;
    private javax.swing.JTextField jQuantity;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblList;
    // End of variables declaration//GEN-END:variables
}
