
import java.awt.Component;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nguyentrinhan2000
 */
public class GUI extends javax.swing.JFrame {
    private Component panel1;
    /**
     * Creates new form GUI
     */
    private boolean testValid() {
        try {
            int soluong = Integer.parseInt(jQuantity.getText());
            int dongia = Integer.parseInt(jMoneyFields.getText());
            if (soluong == 0 && dongia == 0) {
                return false;
            } else {
                return true;
            }
        } catch (Exception e) {
            return false;
        }
    }

    class Checker extends Thread {

        @Override
        public void run() {
            while (true) {
                try {
                    int dongia = Integer.parseInt(jMoneyFields.getText());
                    int soluong = Integer.parseInt(jQuantity.getText());
                    if (dongia != 0) {
                        double KM = 0.0;
                        KM = tinhKM();
                        double result = dongia * soluong * (1 - KM);
                        jMoneyText.setText(String.valueOf(result));
                    } else {
                        throw new Exception();
                    }

                } catch (Exception e) {
                    jMoneyText.setText("0");
                }
            }
        }

    }

    private double tinhKM() {
        double KM = 0.0;
        if (jGuest.isSelected()) {
            KM = 0.0 + 0.0;
        }
        if (jMember.isSelected()) {
            KM += 0.02;
        }
        if (jCou.isSelected()) {
            KM += 0.05;
        }
        if (jHol.isSelected()) {
            KM += 0.1;
        }
        return KM;
    }

    public GUI() {
        initComponents();
        Checker ch = new Checker();
        ch.start();
        jMatHang.addItem("---Chọn---");
        jMatHang.addItem("Trà sữa trân châu");
        jMatHang.addItem("Hồng trà");
        jMatHang.addItem("Matcha");
        jMatHang.addItem("Late kem");
        jMatHang.addItem("Trà sữa thạch");
        Billdefault();
        jGuest.setSelected(true);
    }
    public void Billdefault(){
        jBill.setText("");
        jBill.append("Khách hàng:"+" "+"........." + "\n");
        jBill.append("Số lượng mua:"+" "+"........."+"\n");
        jBill.append("Thức uống:"+" "+"........."+"\n");
        jBill.append("Đơn giá:"+" "+"........."+"\n");
        jBill.append("Ngày:"+" "+"........."+"\n");
        jBill.append("Thanh toán:"+" "+"........."+"\n");
        jBill.append("Trà sữa ONLINE"+"\n");
        jBill.append("***************"+"\n");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jGuestName = new javax.swing.JTextField();
        jQuantity = new javax.swing.JTextField();
        jMatHang = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jMoneyFields = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jBill = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jGiamGia = new javax.swing.JPanel();
        jGuest = new javax.swing.JRadioButton();
        jMember = new javax.swing.JRadioButton();
        jCou = new javax.swing.JCheckBox();
        jHol = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMoneyText = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCal = new javax.swing.JButton();
        jExit = new javax.swing.JButton();
        jDel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chương trình tính tiền");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Khách hàng:");

        jLabel2.setText("Số lượng:");

        jLabel3.setText("Thức uống:");

        jGuestName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuestNameActionPerformed(evt);
            }
        });

        jQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuantityActionPerformed(evt);
            }
        });
        jQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jQuantityKeyReleased(evt);
            }
        });

        jMatHang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMatHang.setName(""); // NOI18N
        jMatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMatHangActionPerformed(evt);
            }
        });

        jLabel4.setText("Đơn giá:");

        jMoneyFields.setEditable(false);
        jMoneyFields.setBackground(new java.awt.Color(153, 153, 153));
        jMoneyFields.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jMoneyFields.setForeground(new java.awt.Color(255, 255, 255));
        jMoneyFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMoneyFieldsActionPerformed(evt);
            }
        });

        jLabel5.setText("VND");

        jLabel6.setText("Thông tin thanh toán");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBill.setColumns(20);
        jBill.setRows(5);
        jScrollPane2.setViewportView(jBill);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel7.setText("Giảm giá:");

        jGiamGia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jGuest.setText("Khách vãng lai");
        jGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuestActionPerformed(evt);
            }
        });

        jMember.setText("Khách hàng thân thiết");
        jMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMemberActionPerformed(evt);
            }
        });

        jCou.setText("Coupon -5%");
        jCou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCouActionPerformed(evt);
            }
        });

        jHol.setText("Dịp lễ -10%");

        javax.swing.GroupLayout jGiamGiaLayout = new javax.swing.GroupLayout(jGiamGia);
        jGiamGia.setLayout(jGiamGiaLayout);
        jGiamGiaLayout.setHorizontalGroup(
            jGiamGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGiamGiaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jGiamGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jGuest)
                    .addComponent(jCou))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jGiamGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMember)
                    .addComponent(jHol))
                .addGap(42, 42, 42))
        );
        jGiamGiaLayout.setVerticalGroup(
            jGiamGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGiamGiaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jGiamGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGuest)
                    .addComponent(jMember))
                .addGap(18, 18, 18)
                .addGroup(jGiamGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCou)
                    .addComponent(jHol))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel8.setText("fb/nguyentrinhan.811");

        jLabel9.setText("Edited by Nhan");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Tổng tiền:");

        jMoneyText.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jMoneyText.setForeground(new java.awt.Color(255, 0, 0));
        jMoneyText.setText("0");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("VND");

        jCal.setText("Tính");
        jCal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCalActionPerformed(evt);
            }
        });

        jExit.setText("Thoát");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        jDel.setText("Xóa");
        jDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jGuestName, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jMoneyFields, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jGiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel10)
                                .addGap(4, 4, 4)
                                .addComponent(jMoneyText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDel)
                                .addGap(94, 94, 94)
                                .addComponent(jExit))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(40, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jGuestName, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jQuantity))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMatHang))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jMoneyFields, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jMoneyText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCal)
                            .addComponent(jExit)
                            .addComponent(jDel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMatHangActionPerformed
        // TODO add your handling code here:
        if (jMatHang.getSelectedIndex() == 0) {
            jMoneyFields.setText("0");
        } else if (jMatHang.getSelectedIndex() == 1) {
            jMoneyFields.setText("15000");
        } else if (jMatHang.getSelectedIndex() == 2) {
            jMoneyFields.setText("20000");
        } else if (jMatHang.getSelectedIndex() == 3) {
            jMoneyFields.setText("25000");
        } else if (jMatHang.getSelectedIndex() == 4) {
            jMoneyFields.setText("45000");
        } else if (jMatHang.getSelectedIndex() == 5) {
            jMoneyFields.setText("30000");
        } else {
            jMoneyFields.setText("0");
        }
    }//GEN-LAST:event_jMatHangActionPerformed

    private void jCouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCouActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCouActionPerformed

    private void jMoneyFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMoneyFieldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMoneyFieldsActionPerformed

    private void jGuestNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuestNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jGuestNameActionPerformed

    private void jCalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCalActionPerformed
        if (jGuest.getText().isEmpty() || jQuantity.getText().isEmpty()){
            JOptionPane.showMessageDialog(panel1, "Lỗi nhập liệu");
        }
        else{
        jBill.setText("");
        jBill.append("Khách hàng:"+" "+jGuestName.getText() + "\n");
        jBill.append("Số lượng mua:"+" "+jQuantity.getText()+"\n");
        jBill.append("Thức uống:"+" "+jMatHang.getItemAt(jMatHang.getSelectedIndex())+"\n");
        jBill.append("Đơn giá:"+" "+jMoneyFields.getText()+"\n");
        jBill.append("Ngày:"+" "+java.time.LocalDateTime.now()+"\n");
        jBill.append("Thanh toán:"+" "+jMoneyText.getText()+ "  VND" +"\n");
        jBill.append("Trà sữa ONLINE"+"\n");
        jBill.append("***************"+"\n");
        }
        
    }//GEN-LAST:event_jCalActionPerformed

    private void jQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jQuantityKeyReleased

    }//GEN-LAST:event_jQuantityKeyReleased

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jExitActionPerformed

    private void jQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQuantityActionPerformed

    private void jMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMemberActionPerformed
        jGuest.setSelected(false);
    }//GEN-LAST:event_jMemberActionPerformed

    private void jGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuestActionPerformed
        jMember.setSelected(false);
    }//GEN-LAST:event_jGuestActionPerformed

    private void jDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDelActionPerformed
        Billdefault();
        jQuantity.setText("");
        jGuestName.setText("");
        jMatHang.setSelectedIndex(0);
        jGuest.setSelected(true);
        jMember.setSelected(false);
        jCou.setSelected(false);
        jHol.setSelected(false);
    }//GEN-LAST:event_jDelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog(null, "Bạn có thực sự muốn thoát?", "Xác Nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
            this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        } else {
            this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea jBill;
    private javax.swing.JButton jCal;
    private javax.swing.JCheckBox jCou;
    private javax.swing.JButton jDel;
    private javax.swing.JButton jExit;
    private javax.swing.JPanel jGiamGia;
    private javax.swing.JRadioButton jGuest;
    private javax.swing.JTextField jGuestName;
    private javax.swing.JCheckBox jHol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jMatHang;
    private javax.swing.JRadioButton jMember;
    private javax.swing.JTextField jMoneyFields;
    private javax.swing.JLabel jMoneyText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jQuantity;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
