package GUI;

/**
 *
 * @author nguyentrinhan.dev
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        setUp();
    }

    public void setUp() {
        if (txtTextArea.getText().equals("")) {
            mnItemCut.setEnabled(false);
            mnItemCopy.setEnabled(false);
            mnItemPaste.setEnabled(false);
            mnItemDelete.setEnabled(false);
            mnItemSelectAll.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnEdit = new javax.swing.JMenu();
        mnItemCopy = new javax.swing.JMenuItem();
        mnItemCut = new javax.swing.JMenuItem();
        mnItemPaste = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnItemDelete = new javax.swing.JMenuItem();
        mnItemSelectAll = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Notepad");

        txtTextArea.setColumns(20);
        txtTextArea.setRows(5);
        txtTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTextAreaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtTextArea);

        jMenu1.setText("File");
        jMenu1.setPreferredSize(new java.awt.Dimension(35, 25));
        jMenuBar1.add(jMenu1);

        mnEdit.setText("Edit");
        mnEdit.setMinimumSize(new java.awt.Dimension(35, 25));
        mnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEditActionPerformed(evt);
            }
        });

        mnItemCopy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnItemCopy.setText("Copy");
        mnItemCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemCopyActionPerformed(evt);
            }
        });
        mnEdit.add(mnItemCopy);

        mnItemCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mnItemCut.setText("Cut");
        mnItemCut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemCutActionPerformed(evt);
            }
        });
        mnEdit.add(mnItemCut);

        mnItemPaste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        mnItemPaste.setText("Paste");
        mnItemPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemPasteActionPerformed(evt);
            }
        });
        mnEdit.add(mnItemPaste);
        mnEdit.add(jSeparator1);

        mnItemDelete.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        mnItemDelete.setText("Delete");
        mnItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemDeleteActionPerformed(evt);
            }
        });
        mnEdit.add(mnItemDelete);

        mnItemSelectAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnItemSelectAll.setText("Select All");
        mnItemSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemSelectAllActionPerformed(evt);
            }
        });
        mnEdit.add(mnItemSelectAll);

        jMenuBar1.add(mnEdit);

        jMenu3.setText("Help");
        jMenu3.setPreferredSize(new java.awt.Dimension(35, 25));
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnItemCutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemCutActionPerformed
        // TODO add your handling code here:
        txtTextArea.cut();
    }//GEN-LAST:event_mnItemCutActionPerformed

    private void mnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnEditActionPerformed

    private void mnItemCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemCopyActionPerformed
        // TODO add your handling code here:
        txtTextArea.copy();
    }//GEN-LAST:event_mnItemCopyActionPerformed

    private void mnItemPasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemPasteActionPerformed
        // TODOa add your handling code here:
        txtTextArea.paste();
    }//GEN-LAST:event_mnItemPasteActionPerformed

    private void mnItemSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemSelectAllActionPerformed
        // TODO add your handling code here:
        txtTextArea.selectAll();
    }//GEN-LAST:event_mnItemSelectAllActionPerformed

    private void mnItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemDeleteActionPerformed
        // TODO add your handling code here:
        txtTextArea.replaceSelection("");
    }//GEN-LAST:event_mnItemDeleteActionPerformed

    private void txtTextAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTextAreaKeyPressed
        // TODO add your handling code here:
        mnItemCut.setEnabled(true);
        mnItemCopy.setEnabled(true);
        mnItemPaste.setEnabled(true);
        mnItemDelete.setEnabled(true);
        mnItemSelectAll.setEnabled(true);

    }//GEN-LAST:event_txtTextAreaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnEdit;
    private javax.swing.JMenuItem mnItemCopy;
    private javax.swing.JMenuItem mnItemCut;
    private javax.swing.JMenuItem mnItemDelete;
    private javax.swing.JMenuItem mnItemPaste;
    private javax.swing.JMenuItem mnItemSelectAll;
    private javax.swing.JTextArea txtTextArea;
    // End of variables declaration//GEN-END:variables
}
