
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nguyentrinhan2000
 */
public class GUI05 extends javax.swing.JFrame {

    /**
     * Creates new form GUI05
     */
    public GUI05() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBackgr = new javax.swing.JMenu();
        jMRED = new javax.swing.JMenuItem();
        jMBLUE = new javax.swing.JMenuItem();
        jMenuForegr = new javax.swing.JMenu();
        jMYELLOW = new javax.swing.JMenuItem();
        jMPINK = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTA = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuOpen = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuClose = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuQuit = new javax.swing.JMenuItem();
        jMenuCustom = new javax.swing.JMenu();
        jCustom1 = new javax.swing.JCheckBoxMenuItem();
        jCustom2 = new javax.swing.JMenu();
        jCustom21 = new javax.swing.JRadioButtonMenuItem();
        jCustom22 = new javax.swing.JRadioButtonMenuItem();

        jMenuBackgr.setText("jMenu1");

        jMRED.setText("jMenuItem1");
        jMenuBackgr.add(jMRED);

        jMBLUE.setText("jMenuItem2");
        jMenuBackgr.add(jMBLUE);

        jPopupMenu1.add(jMenuBackgr);

        jMenuForegr.setText("jMenu1");

        jMYELLOW.setText("jMenuItem2");
        jMenuForegr.add(jMYELLOW);

        jMPINK.setText("jMenuItem1");
        jMenuForegr.add(jMPINK);

        jPopupMenu1.add(jMenuForegr);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUI05 Demo");

        jTA.setColumns(20);
        jTA.setRows(5);
        jScrollPane1.setViewportView(jTA);

        jMenuFile.setText("File");

        jMenuOpen.setText("Open");
        jMenuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuOpen);
        jMenuFile.add(jSeparator1);

        jMenuClose.setText("Close");
        jMenuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCloseActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuClose);
        jMenuFile.add(jSeparator2);

        jMenuQuit.setText("Quit");
        jMenuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuQuit);

        jMenuBar1.add(jMenuFile);

        jMenuCustom.setText("Custom");

        jCustom1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        jCustom1.setSelected(true);
        jCustom1.setText("Custom1");
        jCustom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCustom1ActionPerformed(evt);
            }
        });
        jMenuCustom.add(jCustom1);

        jCustom2.setText("Custom2");

        jCustom21.setSelected(true);
        jCustom21.setText("Custom21");
        jCustom21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCustom21ActionPerformed(evt);
            }
        });
        jCustom2.add(jCustom21);

        jCustom22.setSelected(true);
        jCustom22.setText("Custom22");
        jCustom22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCustom22ActionPerformed(evt);
            }
        });
        jCustom2.add(jCustom22);

        jMenuCustom.add(jCustom2);

        jMenuBar1.add(jMenuCustom);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOpenActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Menu open is clicked");
    }//GEN-LAST:event_jMenuOpenActionPerformed

    private void jMenuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCloseActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Menu close is clicked");
    }//GEN-LAST:event_jMenuCloseActionPerformed

    private void jMenuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuQuitActionPerformed

    private void jCustom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCustom1ActionPerformed
        // TODO add your handling code here:
        if (this.jCustom1.isSelected()){
            JOptionPane.showMessageDialog(this, "Menu custom 1 is selected");
        } else {
            JOptionPane.showMessageDialog(this, "Menu custom 1 is deselected");
        }
    }//GEN-LAST:event_jCustom1ActionPerformed

    private void jCustom21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCustom21ActionPerformed
        // TODO add your handling code here:
        if(this.jCustom21.isSelected()) JOptionPane.showMessageDialog(this, "Menu Custom 21 is selected");
    }//GEN-LAST:event_jCustom21ActionPerformed

    private void jCustom22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCustom22ActionPerformed
        // TODO add your handling code here:
        if(this.jCustom22.isSelected()) JOptionPane.showMessageDialog(this, "Menu Custom 22 is selected");
    }//GEN-LAST:event_jCustom22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBoxMenuItem jCustom1;
    private javax.swing.JMenu jCustom2;
    private javax.swing.JRadioButtonMenuItem jCustom21;
    private javax.swing.JRadioButtonMenuItem jCustom22;
    private javax.swing.JMenuItem jMBLUE;
    private javax.swing.JMenuItem jMPINK;
    private javax.swing.JMenuItem jMRED;
    private javax.swing.JMenuItem jMYELLOW;
    private javax.swing.JMenu jMenuBackgr;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuClose;
    private javax.swing.JMenu jMenuCustom;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuForegr;
    private javax.swing.JMenuItem jMenuOpen;
    private javax.swing.JMenuItem jMenuQuit;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextArea jTA;
    // End of variables declaration//GEN-END:variables
}
